# Generated by Django 4.2.11 on 2024-05-16 12:17

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_messages_day_time_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='day_time',
            field=models.DateTimeField(default=chats.models.now_without_microseconds),
        ),
    ]
