# Generated by Django 4.2.11 on 2024-05-21 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0005_alter_messages_day_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messages",
            old_name="day_time",
            new_name="time",
        ),
    ]
